name: lightseed
description: "Mindfulness app. Seeding a spark of light on a daily basis to its users"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  app_links: ^6.3.3

  english_words: ^4.0.0
  provider: ^6.1.2
  http: ^1.2.2
  google_fonts: ^6.2.1
  intl: ^0.20.1
  lottie: ^3.3.0
  animated_text_kit: ^4.2.2
  shared_preferences: ^2.4.0
  path_provider: ^2.1.5
  supabase_flutter: ^2.8.3
  google_sign_in: ^6.2.2

dev_dependencies:
  test: ^1.16.0
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/logo.png
  - assets/quotes.json
  - assets/animations/

# Add App Icon
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"